// <auto-generated />
using System;
using Jobs.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jobs.Api.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    partial class JobsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jobs.Api.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Jobs.Api.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Closed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ClosingReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("");

                    b.Property<int>("DesiredSalary")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("JobId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Jobs.Api.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId1")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SymDocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ApplicationId1");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Jobs.Api.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Recruiter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecruiterEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("YearlySalary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "TechNova Solutions",
                            Description = "We are looking for a senior backend developer experienced in .NET and distributed systems. The role involves designing scalable APIs, working with microservices architecture, and collaborating closely with frontend and DevOps teams. You will participate in architectural discussions, code reviews, and mentoring junior developers while helping shape the technical direction of the platform.",
                            Location = "Vienna, Austria",
                            Recruiter = "Anna Berger",
                            RecruiterEmail = "anna.berger@technova.com",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Senior Backend Developer",
                            YearlySalary = 85000
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "PixelForge",
                            Description = "Join our product engineering team to build modern web applications using React and TypeScript. The role focuses on implementing responsive UI components, optimizing performance, and collaborating with UX designers and backend developers. You will contribute to design systems and ensure accessibility and maintainability of the frontend codebase.",
                            Location = "Berlin, Germany",
                            Recruiter = "Daniel Schmidt",
                            RecruiterEmail = "daniel.schmidt@pixelforge.io",
                            StartDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Frontend Engineer",
                            YearlySalary = 72000
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "CloudAxis",
                            Description = "We are seeking a DevOps engineer to help automate infrastructure and improve deployment pipelines. The role involves working with Kubernetes, CI/CD systems, and cloud platforms to ensure reliability and scalability. You will collaborate with development teams to streamline release cycles and monitor system performance.",
                            Location = "Munich, Germany",
                            Recruiter = "Laura Weber",
                            RecruiterEmail = "laura.weber@cloudaxis.io",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "DevOps Engineer",
                            YearlySalary = 80000
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "BridgeSoft",
                            Description = "As a full stack developer you will work across both backend and frontend systems, implementing new product features and improving existing services. The position involves working with .NET, REST APIs, relational databases, and modern JavaScript frameworks while collaborating with designers and product managers.",
                            Location = "Prague, Czech Republic",
                            Recruiter = "Martin Novak",
                            RecruiterEmail = "martin.novak@bridgesoft.cz",
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Full Stack Developer",
                            YearlySalary = 70000
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Alpine Digital",
                            Description = "We are hiring a software architect responsible for defining system architecture and technical standards across multiple development teams. The role requires deep expertise in distributed systems, cloud architecture, and design patterns. You will guide technical decisions and ensure maintainability, performance, and scalability.",
                            Location = "Zurich, Switzerland",
                            Recruiter = "Sophie Keller",
                            RecruiterEmail = "sophie.keller@alpinedigital.ch",
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Architect",
                            YearlySalary = 120000
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "AppWorks",
                            Description = "Develop high quality mobile applications for iOS and Android platforms. You will work with cross platform frameworks and native integrations to build performant and user friendly applications. Collaboration with product managers and designers is key to delivering engaging user experiences.",
                            Location = "Budapest, Hungary",
                            Recruiter = "Peter Horvath",
                            RecruiterEmail = "peter.horvath@appworks.hu",
                            StartDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mobile App Developer",
                            YearlySalary = 65000
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "QualityFirst",
                            Description = "The QA automation engineer will design and maintain automated test suites for our web and backend services. Responsibilities include writing integration tests, maintaining testing frameworks, and collaborating with developers to ensure product quality throughout the development lifecycle.",
                            Location = "Warsaw, Poland",
                            Recruiter = "Katarzyna Lewandowska",
                            RecruiterEmail = "k.lewandowska@qualityfirst.pl",
                            StartDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "QA Automation Engineer",
                            YearlySalary = 60000
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "DataBridge",
                            Description = "Design and maintain data pipelines that process and transform large volumes of data. The role involves working with ETL processes, distributed data systems, and cloud storage platforms. You will help ensure reliable data availability for analytics and machine learning workloads.",
                            Location = "Amsterdam, Netherlands",
                            Recruiter = "Tom Van Dijk",
                            RecruiterEmail = "tom.vandijk@databridge.nl",
                            StartDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Engineer",
                            YearlySalary = 78000
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Nordic AI Labs",
                            Description = "Work with data scientists and engineers to deploy machine learning models into production environments. Responsibilities include optimizing model performance, building scalable pipelines, and integrating predictive services into production systems.",
                            Location = "Stockholm, Sweden",
                            Recruiter = "Erik Johansson",
                            RecruiterEmail = "erik.j@nordicai.se",
                            StartDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Machine Learning Engineer",
                            YearlySalary = 95000
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "SecureNet",
                            Description = "Protect company systems and infrastructure by identifying vulnerabilities and implementing security controls. You will conduct security audits, monitor incidents, and collaborate with engineering teams to maintain compliance with modern security standards.",
                            Location = "Vienna, Austria",
                            Recruiter = "Michael Gruber",
                            RecruiterEmail = "m.gruber@securenet.at",
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cybersecurity Specialist",
                            YearlySalary = 88000
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "BrightApps",
                            Description = "Lead the development of digital products by coordinating between engineering, design, and business stakeholders. You will define product roadmaps, gather requirements, and ensure the successful delivery of new features aligned with customer needs.",
                            Location = "London, UK",
                            Recruiter = "Emily Carter",
                            RecruiterEmail = "emily.carter@brightapps.co.uk",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Product Manager",
                            YearlySalary = 90000
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "DesignFlow",
                            Description = "Design intuitive and visually appealing interfaces for web and mobile products. The role involves user research, wireframing, prototyping, and collaborating with developers to translate design concepts into functional interfaces.",
                            Location = "Copenhagen, Denmark",
                            Recruiter = "Lars Petersen",
                            RecruiterEmail = "lars.petersen@designflow.dk",
                            StartDate = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "UI/UX Designer",
                            YearlySalary = 68000
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "Nimbus Tech",
                            Description = "Help organizations migrate and operate workloads in cloud environments such as AWS or Azure. Responsibilities include architecture design, cost optimization, and implementing infrastructure as code for scalable deployments.",
                            Location = "Dublin, Ireland",
                            Recruiter = "Sean Murphy",
                            RecruiterEmail = "sean.murphy@nimbustech.ie",
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cloud Solutions Engineer",
                            YearlySalary = 87000
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Arctic Games",
                            Description = "Join our creative development team to build immersive gameplay experiences. You will work with modern game engines, optimize performance, and collaborate with artists and designers to deliver engaging interactive worlds.",
                            Location = "Helsinki, Finland",
                            Recruiter = "Janne Korhonen",
                            RecruiterEmail = "janne.k@arcticgames.fi",
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game Developer",
                            YearlySalary = 70000
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "DataCore",
                            Description = "Maintain and optimize relational databases supporting mission critical applications. Duties include monitoring performance, managing backups, tuning queries, and ensuring high availability and data integrity across environments.",
                            Location = "Bratislava, Slovakia",
                            Recruiter = "Ivana Kovac",
                            RecruiterEmail = "ivana.kovac@datacore.sk",
                            StartDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Database Administrator",
                            YearlySalary = 72000
                        },
                        new
                        {
                            Id = 16,
                            CompanyName = "OfficeTech",
                            Description = "Provide technical support to internal staff and maintain company IT infrastructure. Tasks include troubleshooting hardware and software issues, managing user accounts, and ensuring smooth daily operation of internal systems.",
                            Location = "Vienna, Austria",
                            Recruiter = "Stefan Hofer",
                            RecruiterEmail = "stefan.hofer@officetech.at",
                            StartDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "IT Support Engineer",
                            YearlySalary = 48000
                        },
                        new
                        {
                            Id = 17,
                            CompanyName = "Insight Consulting",
                            Description = "Analyze business processes and translate requirements into technical specifications. You will work closely with stakeholders to improve operational efficiency and support the delivery of technology driven solutions.",
                            Location = "Frankfurt, Germany",
                            Recruiter = "Julia Fischer",
                            RecruiterEmail = "julia.fischer@insightconsult.de",
                            StartDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Business Analyst",
                            YearlySalary = 75000
                        },
                        new
                        {
                            Id = 18,
                            CompanyName = "ScaleOps",
                            Description = "Ensure the reliability and scalability of large scale production systems. Responsibilities include monitoring infrastructure, responding to incidents, improving observability, and automating operational processes.",
                            Location = "Barcelona, Spain",
                            Recruiter = "Carlos Ruiz",
                            RecruiterEmail = "c.ruiz@scaleops.es",
                            StartDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Site Reliability Engineer",
                            YearlySalary = 86000
                        },
                        new
                        {
                            Id = 19,
                            CompanyName = "MicroTech Systems",
                            Description = "Develop firmware and low level software for embedded hardware platforms. You will work with microcontrollers, communication protocols, and real time operating systems in collaboration with hardware engineering teams.",
                            Location = "Stuttgart, Germany",
                            Recruiter = "Thomas Bauer",
                            RecruiterEmail = "t.bauer@microtech.de",
                            StartDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Embedded Systems Engineer",
                            YearlySalary = 83000
                        },
                        new
                        {
                            Id = 20,
                            CompanyName = "DocuCraft",
                            Description = "Create clear and comprehensive documentation for software products and developer APIs. You will collaborate with engineers and product managers to produce guides, tutorials, and technical references for users.",
                            Location = "Remote",
                            Recruiter = "Rachel Evans",
                            RecruiterEmail = "rachel.evans@docucraft.io",
                            StartDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Technical Writer",
                            YearlySalary = 62000
                        },
                        new
                        {
                            Id = 21,
                            CompanyName = "ChainWave",
                            Description = "Build decentralized applications and smart contracts using modern blockchain frameworks. The role involves designing secure contract logic, integrating blockchain APIs, and maintaining distributed ledger infrastructure.",
                            Location = "Lisbon, Portugal",
                            Recruiter = "Miguel Santos",
                            RecruiterEmail = "miguel.santos@chainwave.pt",
                            StartDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blockchain Developer",
                            YearlySalary = 92000
                        },
                        new
                        {
                            Id = 22,
                            CompanyName = "FutureMind Labs",
                            Description = "Conduct applied research in artificial intelligence and help transform research prototypes into scalable software solutions. You will collaborate with academic partners and internal engineering teams on innovative AI projects.",
                            Location = "Zurich, Switzerland",
                            Recruiter = "Nina Roth",
                            RecruiterEmail = "nina.roth@futuremind.ch",
                            StartDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI Research Engineer",
                            YearlySalary = 110000
                        },
                        new
                        {
                            Id = 23,
                            CompanyName = "NetSecure",
                            Description = "Design and maintain secure network infrastructure supporting enterprise services. Responsibilities include configuring routers and switches, monitoring traffic, and ensuring reliable connectivity across multiple sites.",
                            Location = "Hamburg, Germany",
                            Recruiter = "Oliver Brandt",
                            RecruiterEmail = "oliver.brandt@netsecure.de",
                            StartDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Network Engineer",
                            YearlySalary = 73000
                        },
                        new
                        {
                            Id = 24,
                            CompanyName = "VisionXR",
                            Description = "Develop immersive augmented and virtual reality applications for enterprise and consumer use. The role includes working with 3D environments, interaction systems, and performance optimization for real time rendering.",
                            Location = "Paris, France",
                            Recruiter = "Claire Dubois",
                            RecruiterEmail = "claire.dubois@visionxr.fr",
                            StartDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AR/VR Developer",
                            YearlySalary = 84000
                        },
                        new
                        {
                            Id = 25,
                            CompanyName = "StratEdge",
                            Description = "Lead cross functional software projects from planning through delivery. You will coordinate teams, manage timelines, mitigate risks, and ensure successful implementation of complex technical initiatives.",
                            Location = "Vienna, Austria",
                            Recruiter = "Patrick Leitner",
                            RecruiterEmail = "patrick.leitner@stratedge.at",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Technical Project Manager",
                            YearlySalary = 91000
                        },
                        new
                        {
                            Id = 26,
                            CompanyName = "NextGen Software",
                            Description = "Entry level role for developers eager to grow their skills in modern software engineering. You will work alongside experienced engineers to implement features, fix bugs, and learn best practices in professional development environments.",
                            Location = "Graz, Austria",
                            Recruiter = "Lisa Maier",
                            RecruiterEmail = "lisa.maier@nextgen.at",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Junior Software Developer",
                            YearlySalary = 45000
                        },
                        new
                        {
                            Id = 27,
                            CompanyName = "EuroSystems",
                            Description = "Design and maintain complex enterprise systems that support critical business operations. Responsibilities include infrastructure planning, integration of services, and ensuring system stability and performance.",
                            Location = "Milan, Italy",
                            Recruiter = "Marco Bianchi",
                            RecruiterEmail = "marco.bianchi@eurosystems.it",
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Systems Engineer",
                            YearlySalary = 77000
                        },
                        new
                        {
                            Id = 28,
                            CompanyName = "ShopScale",
                            Description = "Develop scalable backend systems powering high traffic e-commerce platforms. You will implement payment integrations, optimize checkout flows, and ensure high availability during peak demand periods.",
                            Location = "Warsaw, Poland",
                            Recruiter = "Adam Zielinski",
                            RecruiterEmail = "adam.zielinski@shopscale.pl",
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "E-commerce Platform Engineer",
                            YearlySalary = 74000
                        },
                        new
                        {
                            Id = 29,
                            CompanyName = "MetricFlow",
                            Description = "Bridge the gap between data engineering and analytics by designing robust data models and transformation pipelines. The role focuses on making clean, well structured data available for business intelligence and reporting.",
                            Location = "Amsterdam, Netherlands",
                            Recruiter = "Sanne Visser",
                            RecruiterEmail = "sanne.visser@metricflow.nl",
                            StartDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Analytics Engineer",
                            YearlySalary = 79000
                        },
                        new
                        {
                            Id = 30,
                            CompanyName = "NordPlatform",
                            Description = "Build and maintain internal developer platforms that improve engineering productivity. Responsibilities include creating automation tools, maintaining CI/CD pipelines, and ensuring consistent development environments across teams.",
                            Location = "Oslo, Norway",
                            Recruiter = "Anders Larsen",
                            RecruiterEmail = "anders.larsen@nordplatform.no",
                            StartDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Platform Engineer",
                            YearlySalary = 88000
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "abccf311-276d-4b72-ac45-390017f36c8c",
                            ConcurrencyStamp = "83715b5c-ed78-43b9-a0ea-aaccd16b164b",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "e6da29bc-3c78-4134-9b6f-fd273fa2cc56",
                            ConcurrencyStamp = "204d473f-802a-4d08-ac56-5a3115a52f44",
                            Name = "Applicant"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Jobs.Api.Entities.Application", b =>
                {
                    b.HasOne("Jobs.Api.Entities.AppUser", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jobs.Api.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Jobs.Api.Entities.Document", b =>
                {
                    b.HasOne("Jobs.Api.Entities.Application", null)
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobs.Api.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Jobs.Api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Jobs.Api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobs.Api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Jobs.Api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jobs.Api.Entities.Application", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
